server {
    listen 8020;
    server_name localhost;

    root /usr/share/nginx/html;

    location /local/sta/http/ {
        index index.html;
        try_files /index.html =404;
    }

    location /local/download/index {
        alias /usr/share/nginx/html/index.html;
        add_header Content-Disposition 'attachment; filename="index.html"';
        add_header Content-Type 'application/octet-stream';
    }
}